import type { Employee } from './TablePage';

export const employees: Employee[] = [
    {
        id: 1,
        name: 'John Smith',
        email: 'john@example.com',
        department: 'Engineering',
        salary: 95000,
        startDate: '2020-03-15',
    },
    {
        id: 2,
        name: 'Sarah Johnson',
        email: 'sarah@example.com',
        department: 'Marketing',
        salary: 78000,
        startDate: '2019-07-22',
    },
    {
        id: 3,
        name: 'Michael Chen',
        email: 'michael@example.com',
        department: 'Engineering',
        salary: 102000,
        startDate: '2018-11-08',
    },
    {
        id: 4,
        name: 'Emily Davis',
        email: 'emily@example.com',
        department: 'Sales',
        salary: 85000,
        startDate: '2021-01-10',
    },
    {
        id: 5,
        name: 'Robert Wilson',
        email: 'robert@example.com',
        department: 'HR',
        salary: 72000,
        startDate: '2020-09-03',
    },
    {
        id: 6,
        name: 'Lisa Anderson',
        email: 'lisa@example.com',
        department: 'Engineering',
        salary: 98000,
        startDate: '2019-05-17',
    },
    {
        id: 7,
        name: 'David Martinez',
        email: 'david@example.com',
        department: 'Finance',
        salary: 88000,
        startDate: '2021-06-25',
    },
    {
        id: 8,
        name: 'Jennifer Taylor',
        email: 'jennifer@example.com',
        department: 'Marketing',
        salary: 81000,
        startDate: '2020-12-14',
    },
    {
        id: 9,
        name: 'Thomas Brown',
        email: 'thomas@example.com',
        department: 'Engineering',
        salary: 105000,
        startDate: '2017-04-19',
    },
    {
        id: 10,
        name: 'Maria Gonzalez',
        email: 'maria@example.com',
        department: 'Sales',
        salary: 83000,
        startDate: '2022-02-11',
    },
    {
        id: 11,
        name: 'James Walker',
        email: 'james@example.com',
        department: 'Finance',
        salary: 92000,
        startDate: '2019-10-05',
    },
    {
        id: 12,
        name: 'Patricia Lee',
        email: 'patricia@example.com',
        department: 'HR',
        salary: 76000,
        startDate: '2021-09-30',
    },
    {
        id: 13,
        name: 'Kevin Adams',
        email: 'kevin@example.com',
        department: 'Engineering',
        salary: 99000,
        startDate: '2018-06-14',
    },
    {
        id: 14,
        name: 'Sophia Turner',
        email: 'sophia@example.com',
        department: 'Marketing',
        salary: 79000,
        startDate: '2020-11-01',
    },
    {
        id: 15,
        name: 'Andrew Scott',
        email: 'andrew@example.com',
        department: 'Finance',
        salary: 87000,
        startDate: '2022-07-18',
    },
    {
        id: 16,
        name: 'Olivia Harris',
        email: 'olivia@example.com',
        department: 'Sales',
        salary: 82000,
        startDate: '2019-03-22',
    },
    {
        id: 17,
        name: 'Christopher Young',
        email: 'chris@example.com',
        department: 'Engineering',
        salary: 108000,
        startDate: '2017-12-28',
    },
    {
        id: 18,
        name: 'Hannah Baker',
        email: 'hannah@example.com',
        department: 'HR',
        salary: 74000,
        startDate: '2020-05-07',
    },
    {
        id: 19,
        name: 'Jonathan Reed',
        email: 'jonathan@example.com',
        department: 'Marketing',
        salary: 80000,
        startDate: '2021-04-13',
    },
    {
        id: 20,
        name: 'Victoria Perez',
        email: 'victoria@example.com',
        department: 'Finance',
        salary: 93000,
        startDate: '2018-08-26',
    },
];
